# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rake db:seed (or created alongside the db with db:setup).
#
# Examples:
#
#   cities = City.create([{ name: 'Chicago' }, { name: 'Copenhagen' }])
#   Mayor.create(name: 'Emanuel', city: cities.first)

languages = ProgrammingLanguage.create([
  { language: 'PHP' },
  { language: 'JavaScript' },
  { language: 'Python' },
  { language: 'ASP.NET' },
  { language: 'Apex' },
  { language: 'Java' },
  { language: 'Ruby' },
  { language: 'C++' },
  { language: 'C#' },
  { language: 'C' },
  { language: 'Go' },
  { language: 'Perl' },
  { language: 'Swift' },
  { language: 'Haskell' },
  { language: 'Lua' },
  { language: 'Scala' },
  { language: 'Clojure' },
  { language: 'Groovy' },
  { language: 'Objective-C' },
  { language: 'R' },
  { language: 'Erlang' },
  { language: 'Elixir' },
  { language: 'Dart' },
  { language: 'Rust' },
  { language: 'F#' },
  { language: 'OCaml' }
])

companies = Company.create([
  { name: "Wells Fargo", url: '', num_female_eng: 1296, num_eng: 5407 },
  { name: "ThoughtWorks", num_female_eng: 337, num_eng: 1425 },
  { name: "Mozilla", num_female_eng: 43, num_eng: 500 },
  { name: "Dropbox", num_female_eng: 42, num_eng: 384 },
  { name: "Pinterest", num_female_eng: 60, num_eng: 307 },
  { name: "Airbnb", num_female_eng: 38, num_eng: 281 },
  { name: "Qualcomm", num_female_eng: 15, num_eng: 271 },
  { name: "The Washington Post", num_female_eng: 31, num_eng: 217 },
  { name: "Yelp", num_female_eng: 17, num_eng: 206 },
  { name: "PayPal", num_female_eng: 11, num_eng: 163 },
  { name: "New Relic", num_female_eng: 30, num_eng: 151 },
  { name: "Etsy", num_female_eng: 19, num_eng: 149 },
  { name: "Guidewire Software", num_female_eng: 21, num_eng: 122 },
  { name: "Lookout", num_female_eng: 9, num_eng: 112 },
  { name: "Quantcast", num_female_eng: 15, num_eng: 112 },
  { name: "Gilt", num_female_eng: 11, num_eng: 111 },
  { name: "Nearsoft, Inc.", num_female_eng: 3, num_eng: 107 },
  { name: "HubSpot", num_female_eng: 13, num_eng: 105 },
  { name: "GitHub", num_female_eng: 14, num_eng: 104 },
  { name: "foursquare", num_female_eng: 6, num_eng: 85 },
  { name: "Wikimedia Foundation", num_female_eng: 9, num_eng: 82 },
  { name: "Stripe", num_female_eng: 9, num_eng: 81 },
  { name: "City of Los Angeles Information Technology Agency", num_female_eng: 33, num_eng: 78 },
  { name: "Rhapsody", num_female_eng: 14, num_eng: 76 },
  { name: "Eventbrite", num_female_eng: 14, num_eng: 74 },
  { name: "Practice Fusion", num_female_eng: 12, num_eng: 72 },
  { name: "Slack", num_female_eng: 13, num_eng: 71 },
  { name: "10up", num_female_eng: 8, num_eng: 67 },
  { name: "The Motley Fool", num_female_eng: 10, num_eng: 64 },
  { name: "Delphix", num_female_eng: 3, num_eng: 64 },
  { name: "PDX, Inc.", num_female_eng: 13, num_eng: 63 },
  { name: "Redfin", num_female_eng: 11, num_eng: 61 },
  { name: "Flipboard", num_female_eng: 6, num_eng: 60 },
  { name: "SalesforceIQ", num_female_eng: 3, num_eng: 57 },
  { name: "Rdio", num_female_eng: 9, num_eng: 56 },
  { name: "NGP VAN", num_female_eng: 15, num_eng: 56 },
  { name: "Capsher Technology", num_female_eng: 4, num_eng: 55 },
  { name: "Elemental Technologies", num_female_eng: 6, num_eng: 55 },
  { name: "if(we)", num_female_eng: 8, num_eng: 53 },
  { name: "Hearsay Social", num_female_eng: 10, num_eng: 52 },
  { name: "SurveyMonkey", num_female_eng: 9, num_eng: 52 },
  { name: "Change.org, Inc.", num_female_eng: 15, num_eng: 52 },
  { name: "Polyvore", num_female_eng: 13, num_eng: 50 },
  { name: "Intercom", num_female_eng: 3, num_eng: 50 },
  { name: "AYASDI", num_female_eng: 16, num_eng: 49 },
  { name: "AdRoll", num_female_eng: 6, num_eng: 48 },
  { name: "Mapbox", num_female_eng: 10, num_eng: 48 },
  { name: "POPSUGAR", num_female_eng: 8, num_eng: 46 },
  { name: "DramaFever", num_female_eng: 5, num_eng: 46 },
  { name: "thoughtbot", num_female_eng: 5, num_eng: 45 },
  { name: "Perforce", num_female_eng: 6, num_eng: 45 },
  { name: "Edmodo", num_female_eng: 1, num_eng: 45 },
  { name: "Zendesk", num_female_eng: 8, num_eng: 45 },
  { name: "Yahoo", num_female_eng: 4, num_eng: 42 },
  { name: "HootSuite", num_female_eng: 6, num_eng: 41 },
  { name: "Ellation (fka Crunchyroll)", num_female_eng: 2, { num_eng: 40 },
  { name: "Stack Exchange", num_female_eng: 3, num_eng: 40 },
  { name: "Outpace Systems", num_female_eng: 4, num_eng: 40 },
  { name: "VSCO", num_female_eng: 7, num_eng: 40 },
  { name: "Vungle", num_female_eng: 5, num_eng: 40 },
  { name: "Khan Academy", num_female_eng: 10, num_eng: 39 },
  { name: "Intent Media", num_female_eng: 8, num_eng: 39 },
  { name: "uSwitch, London", num_female_eng: 1, num_eng: 38 },
  { name: "Birchbox", num_female_eng: 8, num_eng: 36 },
  { name: "Medium", num_female_eng: 10, num_eng: 36 },
  { name: "Indiegogo", num_female_eng: 7, num_eng: 36 },
  { name: "Simply Measured", num_female_eng: 6, num_eng: 35 },
  { name: "Quora", num_female_eng: 4, num_eng: 35 },
  { name: "TheLadders", num_female_eng: 6, num_eng: 35 },
  { name: "EnergySavvy", num_female_eng: 7, num_eng: 35 },
  { name: "Manilla, LLC", num_female_eng: 10, num_eng: 32 },
  { name: "Venmo", num_female_eng: 5, num_eng: 32 },
  { name: "Rent the Runway", num_female_eng: 7, num_eng: 32 },
  { name: "Shoplocal", num_female_eng: 5, num_eng: 31 },
  { name: "Refinery29", num_female_eng: 9, num_eng: 31 },
  { name: "Minted", num_female_eng: 4, num_eng: 31 },
  { name: "Tapad", num_female_eng: 1, num_eng: 31 },
  { name: "Activision", num_female_eng: 1, num_eng: 30 },
  { name: "PagerDuty", num_female_eng: 1, num_eng: 29 },
  { name: "Enstoa, Inc.", num_female_eng: 11, num_eng: 29 },
  { name: "Bibliocommons", num_female_eng: 6, num_eng: 29 },
  { name: "Inkling", num_female_eng: 2, num_eng: 29 },
  { name: "Addepar", num_female_eng: 1, num_eng: 29 },
  { name: "Nextdoor", num_female_eng: 0, num_eng: 29 },
  { name: "Moovweb", num_female_eng: 7, num_eng: 29 },
  { name: "Paperless Post", num_female_eng: 4, num_eng: 28 },
  { name: "PlanGrid", num_female_eng: 7, num_eng: 26 },
  { name: "Cognitect", num_female_eng: 2, num_eng: 25 },
  { name: "Causes.com", num_female_eng: 2, num_eng: 25 },
  { name: "Monetate", num_female_eng: 11, num_eng: 25 },
  { name: "Learnist", num_female_eng: 1, num_eng: 25 },
  { name: "FreshBooks.com", num_female_eng: 5, num_eng: 25 },
  { name: "Clever", num_female_eng: 4, num_eng: 25 },
  { name: "Goodreads", num_female_eng: 5, num_eng: 25 },
  { name: "Coinbase", num_female_eng: 1, num_eng: 24 },
  { name: "Shopatron", num_female_eng: 3, num_eng: 24 },
  { name: "Hipmunk", num_female_eng: 3, num_eng: 24 },
  { name: "Coursera", num_female_eng: 2, num_eng: 24 },
  { name: "Orbis Technologies", num_female_eng: 4, num_eng: 24 },
  { name: "Disqus", num_female_eng: 3, num_eng: 23 },
  { name: "WibiData", num_female_eng: 6, num_eng: 23 },
  { name: "Udacity", num_female_eng: 3, num_eng: 23 },
  { name: "Wave Apps", num_female_eng: 5, num_eng: 23 },
  { name: "Incognito Software", num_female_eng: 4, num_eng: 23 },
  { name: "Kiva", num_female_eng: 3, num_eng: 23 },
  { name: "Mindjet", num_female_eng: 8, num_eng: 22 },
  { name: "Lanetix", num_female_eng: 4, num_eng: 22 },
  { name: "OmniTI", num_female_eng: 5, num_eng: 22 },
  { name: "Guidebook", num_female_eng: 0, num_eng: 22 },
  { name: "Narrative Science", num_female_eng: 3, num_eng: 21 },
  { name: "7digital", num_female_eng: 1, num_eng: 21 },
  { name: "Kanjoya", num_female_eng: 4, num_eng: 21 },
  { name: "The New York Times", num_female_eng: 3, num_eng: 21 },
  { name: "Liferay", num_female_eng: 2, num_eng: 21 },
  { name: "Sunrun", num_female_eng: 6, num_eng: 21 },
  { name: "Asana", num_female_eng: 3, num_eng: 21 },
  { name: "Basecamp", num_female_eng: 1, num_eng: 20 },
  { name: "Bitly", num_female_eng: 4, num_eng: 20 },
  { name: "Fog Creek Software", num_female_eng: 0, num_eng: 20 },
  { name: "Sailthru", num_female_eng: 5, num_eng: 20 },
  { name: "HowAboutWe", num_female_eng: 4, num_eng: 20 },
  { name: "Treehouse", num_female_eng: 2, num_eng: 19 },
  { name: "shopkick", num_female_eng: 2, num_eng: 19 },
  { name: "WePay", num_female_eng: 4, num_eng: 19 },
  { name: "Birst", num_female_eng: 1, num_eng: 19 },
  { name: "Reverb", num_female_eng: 2, num_eng: 18 },
  { name: "Code School", num_female_eng: 4, num_eng: 18 },
  { name: "New Bamboo, London", num_female_eng: 2, num_eng: 16 },
  { name: "Sosh", num_female_eng: 2, num_eng: 16 },
  { name: "Versal", num_female_eng: 3, num_eng: 16 },
  { name: "Yummly", num_female_eng: 4, num_eng: 16 },
  { name: "thredUP", num_female_eng: 5, num_eng: 15 },
  { name: "Selerity", num_female_eng: 2, num_eng: 15 },
  { name: "Blend Labs", num_female_eng: 5, num_eng: 15 },
  { name: "Wanelo", num_female_eng: 3, num_eng: 15 },
  { name: "One Medical", num_female_eng: 4, num_eng: 15 },
  { name: "Harvest", num_female_eng: 0, num_eng: 15 },
  { name: "Facebook", num_female_eng: 2, num_eng: 15 },
  { name: "Floored", num_female_eng: 6, num_eng: 15 },
  { name: "Apartment List", num_female_eng: 1, num_eng: 15 },
  { name: "Highfive", num_female_eng: 3, num_eng: 14 },
  { name: "BlackLocus", num_female_eng: 6, num_eng: 14 },
  { name: "Moontoast", num_female_eng: 0, num_eng: 14 },
  { name: "Collective IDea", num_female_eng: 0, num_eng: 14 },
  { name: "Reddit", num_female_eng: 2, num_eng: 14 },
  { name: "Quip", num_female_eng: 4, num_eng: 14 },
  { name: "StackMob", num_female_eng: 0, num_eng: 14 },
  { name: "Wealthfront", num_female_eng: 4, num_eng: 13 },
  { name: "Noom", num_female_eng: 3, num_eng: 13 },
  { name: "Snapchat", num_female_eng: 2, num_eng: 13 },
  { name: "npm", num_female_eng: 6, num_eng: 13 },
  { name: "Optimizely", num_female_eng: 1, num_eng: 12 },
  { name: "Imgur", num_female_eng: 1, num_eng: 12 },
  { name: "Radius.com", num_female_eng: 3, num_eng: 12 },
  { name: "Think Brownstone", num_female_eng: 5, num_eng: 12 },
  { name: "GameChanger.io", num_female_eng: 1, num_eng: 12 },
  { name: "MyLikes", num_female_eng: 2, num_eng: 12 },
  { name: "Center for Open Science", num_female_eng: 3, num_eng: 11 },
  { name: "Bendyworks", num_female_eng: 4, num_eng: 11 },
  { name: "Noodle", num_female_eng: 4, num_eng: 11 },
  { name: "Billups", num_female_eng: 3, num_eng: 11 },
  { name: "Inductive Automation", num_female_eng: 1, num_eng: 10 },
  { name: "AeroFS", num_female_eng: 1, num_eng: 10 },
  { name: "noise", num_female_eng: 2, num_eng: 10 },
  { name: "Scientific Learning", num_female_eng: 5, num_eng: 10 },
  { name: "creativeLIVE", num_female_eng: 0, num_eng: 10 },
  { name: "Pearson College", num_female_eng: 4, num_eng: 9 },
  { name: "Keen IO", num_female_eng: 1, num_eng: 9 },
  { name: "Topix", num_female_eng: 0, num_eng: 9 },
  { name: "Meteor", num_female_eng: 3, num_eng: 9 },
  { name: "The Slate Group", num_female_eng: 3, num_eng: 9 },
  { name: "Codecademy", num_female_eng: 1, num_eng: 9 },
  { name: "charity water", num_female_eng: 1, num_eng: 8 },
  { name: "Geckoboard", num_female_eng: 2, num_eng: 8 },
  { name: "Massdrop", num_female_eng: 0, num_eng: 8 },
  { name: "Northwest Independent Ruby Development", num_female_eng: 7, num_eng: 8 },
  { name: "square-root.com", num_female_eng: 2, num_eng: 8 },
  { name: "Ticket Evolution", num_female_eng: 2, num_eng: 8 },
  { name: "Ivycorp", num_female_eng: 2, num_eng: 7 },
  { name: "Getable", num_female_eng: 2, num_eng: 7 },
  { name: "doxo", num_female_eng: 0, num_eng: 7 },
  { name: "Datascope Analytics", num_female_eng: 2, num_eng: 7 },
  { name: "Patreon", num_female_eng: 1, num_eng: 7 },
  { name: "Hacker School", num_female_eng: 2, num_eng: 7 },
  { name: "CirrusMio", num_female_eng: 1, num_eng: 7 },
  { name: "Makeshift, London", num_female_eng: 2, num_eng: 7 },
  { name: "Flatiron Health", num_female_eng: 1, num_eng: 7 },
  { name: "Checkout 51", num_female_eng: 0, num_eng: 6 },
  { name: "FirstWatch Solutions", num_female_eng: 0, num_eng: 6 },
  { name: "Tricae", num_female_eng: 1, num_eng: 6 },
  { name: "Skillshare", num_female_eng: 1, num_eng: 6 },
  { name: "Balderdash", num_female_eng: 2, num_eng: 6 },
  { name: "Relay Graduate School", num_female_eng: 1, num_eng: 6 },
  { name: "Pact", num_female_eng: 1, num_eng: 6 },
  { name: "BarkBox", num_female_eng: 2, num_eng: 6 },
  { name: "Cohealo", num_female_eng: 1, num_eng: 6 },
  { name: "The Playforge", num_female_eng: 0, num_eng: 6 },
  { name: "Tindie", num_female_eng: 1, num_eng: 5 },
  { name: "Lot18", num_female_eng: 1, num_eng: 5 },
  { name: "Rolled Alloys", num_female_eng: 1, num_eng: 5 },
  { name: "Findery", num_female_eng: 2, num_eng: 5 },
  { name: "NovoEd", num_female_eng: 1, num_eng: 5 },
  { name: "Adzerk", num_female_eng: 1, num_eng: 5 },
  { name: "Circa", num_female_eng: 0, num_eng: 5 },
  { name: "Kaon Interactive, Inc.", num_female_eng: 0, num_eng: 5 },
  { name: "appssavvy", num_female_eng: 0, num_eng: 5 },
  { name: "Intern Match", num_female_eng: 1, num_eng: 4 },
  { name: "Yahoo!", num_female_eng: 1, num_eng: 4 },
  { name: "The Muse", num_female_eng: 3, num_eng: 4 },
  { name: "Walker & Company Brands", num_female_eng: 2, num_eng: 4 },
  { name: "Sifteo", num_female_eng: 0, num_eng: 4 },
  { name: "Chain.com", num_female_eng: 1, num_eng: 4 },
  { name: "elationemr", num_female_eng: 1, num_eng: 4 },
  { name: "The Slate Group", num_female_eng: 1, num_eng: 4 },
  { name: "Code for America", num_female_eng: 2, num_eng: 4 },
  { name: "Renewable Funding", num_female_eng: 1, num_eng: 4 },
  { name: "Qstream", num_female_eng: 0, num_eng: 3 },
  { name: "Wealthsimple", num_female_eng: 1, num_eng: 3 },
  { name: "PolicyStat", num_female_eng: 0, num_eng: 3 },
  { name: "Hackbright Academy", num_female_eng: 2, num_eng: 3 },
  { name: "Glassbreakers", num_female_eng: 2, num_eng: 3 },
  { name: "Codurance, London", num_female_eng: 0, num_eng: 3 },
  { name: "Hypothes.is", num_female_eng: 0, num_eng: 3 },
  { name: "Goldbely", num_female_eng: 0, num_eng: 3 },
  { name: "circl, Brooklyn", num_female_eng: 0, num_eng: 3 },
  { name: "Wizard Development", num_female_eng: 2, num_eng: 3 },
  { name: "Building Robotics", num_female_eng: 1, num_eng: 3 },
  { name: "ATTN", num_female_eng: 1, num_eng: 3 },
  { name: "Mapistry", num_female_eng: 1, num_eng: 3 },
  { name: "Yellowsmith", num_female_eng: 2, num_eng: 3 },
  { name: "The Last Pickle", num_female_eng: 1, num_eng: 3 },
  { name: "Webkite", num_female_eng: 0, num_eng: 3 },
  { name: "Watsi", num_female_eng: 0, num_eng: 2 },
  { name: "Admittedly", num_female_eng: 1, num_eng: 2 },
  { name: "Spitfire Athlete", num_female_eng: 2, num_eng: 2 },
  { name: "Tetherpad", num_female_eng: 1, num_eng: 2 },
  { name: "Zerocater", num_female_eng: 0, num_eng: 2 },
  { name: "1up talent", num_female_eng: 0, num_eng: 2 },
  { name: "LaunchBit", num_female_eng: 1, num_eng: 2 },
  { name: "Kabinet", num_female_eng: 2, num_eng: 2 },
  { name: "HIPAA Risk Management", num_female_eng: 2, num_eng: 2 },
  { name: "Levo League",num_female_eng: 0, num_eng: 2 },
  { name: "Tog+Porter", num_female_eng: 1, num_eng: 1 }
])